[build]
command = "corepack prepare pnpm@8.5.1 --activate &&  pnpm i  && npx pnpm build"
publish = "build"

[build.environment]
NPM_FLAGS = "--version"
AWS_LAMBDA_JS_RUNTIME = "nodejs16.x"

[functions]
node_bundler = "esbuild"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "seviche.cc"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "style-src 'self' http://fonts.cdnfonts.com/css/lato https://giscus.app/default.css; script-src 'self' 'unsafe-inline' https://*.seviche.cc https://giscus.app https://hexoverc.vercel.app/umami.js https://cdn.splitbee.io/sb.js https://plausiable.seviche.cc/js/script.js"
    Referrer-Policy = "strict-origin-when-cross-origin"
[[redirects]]
  from = "/.well-known/webfinger"
  to = "https://kongwoo.icu/.well-known/webfinger?resource=acct:blog@kongwoo.icu"
  status = 302
  force = true

[[redirects]]
  from = "/.well-known/host-meta"
  to = "https://fed.brid.gy/.well-known/host-meta"
  status = 302
  force = true

[[redirects]]
  from = "/.well-known/host-meta.xrd"
  to = "https://fed.brid.gy/.well-known/host-meta.xrd"
  status = 302
  force = true

[[redirects]]
  from = "/.well-known/host-meta.jrd"
  to = "https://fed.brid.gy/.well-known/host-meta.jrd"
  status = 302
  force = true

[[redirects]]
  from = "/.well-known/webfinger"
  to = "https://fed.brid.gy/.well-known/webfinger"
  status = 302
  force = true